apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml
- priority_class.yaml

patchesStrategicMerge:
- priority_class_patch.yaml

images:
- name: controller
  newName: IMG=testme
  newTag: latest
- name: controller-admission
  newName: IMG=admission-testme
  newTag: latest
