---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kyma-project.io--kim-snatch-to-apiserver
  namespace: kyma-system
  labels:
    purpose: apiserver
spec:
  egress:
    - ports:
        - port: 443
          protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: kim-snatch
  policyTypes:
    - Egress
---